# Generated by Django 3.1.6 on 2021-05-23 12:03

import django.core.validators
from django.db import migrations, models
import webform.ico_validation


class Migration(migrations.Migration):

    dependencies = [
        ('webform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='email',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='form',
            name='ico',
            field=models.CharField(max_length=8, unique=True, validators=[webform.ico_validation.ico_exists]),
        ),
        migrations.AlterField(
            model_name='form',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
